# Get node on alpine from docker hub. alphine is very light_weight
FROM node:alpine
# Copy all files in this fodler to /app folder
COPY . /app
# Specify app directory
WORKDIR /app
# Run command
CMD node app.js